---
title: Amplitude Academia
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: academia@amplitudesolutions.com.br
description: Simple and flexible Jekyll theme for help center.
baseurl: http://academia.amplitudesolutions.com.br/
url: 
twitter_username: amplitudeacademia
github_username: leandrodemedeiros
color_theme: "#0081ff"
color_text: "#fff"
language: en
markdown: kramdown
permalink: "/:title/"
gems:
- jekyll-paginate
paginate: 5
plugins_dir:
- jekyll-admin
